# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d08269d1706f9e452a22dd38137bd6b15143cadcf8bca3cd97e2ce0edab7079e0fb4571e1a2d2c5da20c2908c64ccb8104d0f7dcbe73a474b8fc18ad8dd9379

test:
  secret_key_base: 1320e18e0934bdcc4f8e7abaec7ca09d30dda45f515bf12f396c7c565595db9ef63769a43ac68f25bbdda9a51b3390599a1bf47e5ec964c6802235ecfa78d5a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
